### ISSUE TITLE
API should be on XRSession and always based on the upcoming frame's world state

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#10]
If we have an Asynchronous API on XRFrame, that would mean that the results would be calculated based on the world for that frame but wouldn't be available until prior to the next frame. In the case where, for example, the estimate for the height of a plane that was hit changes, the object may be placed and then rendered in the subsequent frame in a location that would be floating above or embedded in the surface. 

A way to resolve this and to satisfy this line from the explainer: "hopefully it can be guaranteed that the results will be valid at least for the duration of the upcoming frame." - the hit-test should be on XRSession and would always be calculated with respect to the subsequent frame. The order of operations would be:
1) Update the Session to produce the new frame
2) Calculate pending hit-tests against the new frame and then resolve promises with results
3) Invoke the RAF for this frame - any objects that were created based on the promises in (2) will be rendered in an accurate location for this frame.

**Comment by blairmacintyre** [comment]
I generally agree, as we discussed in https://github.com/immersive-web/hit-test/issues/9

I still don't think it's necessary (or practical) to guarantee hit-tests will be resolved before the next frame, because there can be race conditions.  If the hitTest function is called JUST BEFORE the upcoming rAF, we would NOT want to delay the rAF as this will slow frame rate, which can cause visual issues, which is much less desirable than delaying the hit Test by a frame.

So, I think

1. update the session to produce the new frame
2. if there are pending hit-test that have been resolved, resolve their promises
3. invoke rAF. 

The key being that any promises that _can_ be resolved are guaranteed to be resolved before the rAF, but there might be ones that are still unresolved.

**Comment by lincolnfrog** [comment]
Ok, that makes sense. The guarantee is that WHEN the hit-test resolves, it is valid for the subsequent frame. We don't guarantee how many frames may elapse between the hit-test call and the resolution, only that it will make sense for the frame after that resolution. I will update the explainer!

**Comment by lincolnfrog** [comment]
We had a discussion internally that resulted in the following proposed modification:

You have to do your hit-test calls prior to requesting the next frame if you want the results prior to that frame. The rule would be that hit results are guaranteed to resolve prior to the next frame if they were requested prior to requesting that frame. This gives predictability of timing and ensures we avoid the edge-case of requesting a hit-test too close to the next RAF for the results to be available in time. @blairmacintyre how does that sound?

**Comment by blairmacintyre** [comment]
I assume you mean before you call "requestAnimationFrame()" again? 

In theory, that's better (i.e., if you call hit-test inside your application logic in the rAF, it's guaranteed to resolve before the next rAF, but if you call it outside the rAF method, then it may or may not get resolved before the next frame).

This addresses the race condition concern I have, but not the other one:  are we willing to assert that all implementations of hit-test MUST do this?  What do we do on a platform that provides an async hit test that is not guaranteed to resolve before the next rendering frame?

I admit this is hypothetical, since I'm not implementing all of these platforms. ;)  But, it seems like a show stopper for such a platform.

It's unclear that we need this guarantee, though.  In practice I would imagine a reticle (for example) having a 3D location provided by hit test that it will float over (like on Hololens).  A platform with guarantees like you describe would call hit-test before the end of the rAF, and when the promise resolves, we update the 3D position we'll use for the reticle, thus guaranteeing they have an updated position for the next frame.  Awesome.  

If we don't have this guarantee, what happens?   The code would likely be the same:  when the promise resolves, we update the 3D position we'll use for the reticle.  It it misses a frame, the reticle lags a frame or two behind (however long the resolve takes).  But, that's a characteristic of the platform, and user's would be used to it (after all, other apps on the platform would be using the same API).

The one difference is that the programmer would NOT call the hit test at the end of every rAF, they would only call it when the hit-test resolves (otherwise, outstanding hit-tests could pile up).  Which is "less Awesome".  

Overall, my question to platform folks:  are we comfortable assuming that the platform equivalent of hit-test can resolve like you suggest.  If we are, then this proposal sounds good.

**Comment by ddorwin** [comment]
If the way developers use the API is the same, how many frames it takes to resolve could be a quality-of-implementation issue with a recommendation that it be the next frame. However, @blairmacintyre raises a concern that developers might have to account for this. If so - and also because platforms may have hit-test limits - we might want to add a way for implementations to provide back pressure.

**Comment by blairmacintyre** [comment]
@ddorwin  back pressure on ...?

My preference after thinking about this more is that "quality-of-implementation" is the right way to think about it, and we should do what you suggest here:  implementations should be encouraged to try and hit next-frame, but not guarantee it.

I'm not sure the best pattern for managing limited hit tests.  Lets say, for example, we say platforms can do N at a time, where N is the number of possible "pointers" the platform has;  if they aren't guaranteed to complete, we need a policy and method for managing it.  We could say N / frame, and require implementations to handle N / frame with whatever frame backlog they create by not hitting "the next frame".    If it takes 2-5 frames to resolve hits, the implementation would have to handle 2-5 * N outstanding requests.  On reflection that doesn't seem so bad.  Even with 10 fingers, and N == 10, that wouldn't be a massive number outstanding.  And it makes it simple (N / frame, where each platform imposes a reasonable N).

**Comment by ddorwin** [comment]
@blairmacintyre I meant a way to indicate that the system cannot handle any more hit test requests at this time so the developer can respond appropriately whether that is after 1 request or 100. This would mean developers don't have to worry about N or other calculations. It might still be worth documenting in the spec a (recommended) minimum that should meet the needs of most apps.

**Comment by blairmacintyre** [comment]
Agreed!

**Comment by lincolnfrog** [comment]
The Spec matches the language described in the bug description. The discussion has turned towards rate-limiting and quality-of-service concerns - I think the discussion in this bug is sufficiently captured in the explainer.
