### ISSUE TITLE
support testing intersections with time-swept volumes

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#12]
Original comment: "Perhaps we should ensure that we can extend the API additively to support testing intersections with time-swept volumes."

@kearwood - can you elaborate on what you meant by this?

**Comment by blairmacintyre** [comment]
I assume he meant that since each "frame" of time is actually an interval of time, and a representation of the world could be interpreted as a volume, then a "hittest" is actually a hittest over the whole volume of time represented by the "frame" during which the user/program issues the hittest.  So, you might want to test against "all possible results" from the previous to the next frame (essentially)

**Comment by lincolnfrog** [comment]
Is this addressed adequately by the notion of the frame-of-reference parameter being able to be supplied as the frame of reference of the device with a relative vector? This means you can at least get either the beginning of the sweep (using absolute vector) or the end of the sweep (using relative vector).

**Comment by blairmacintyre** [comment]
I think it is probably covered, if only because it seems "adequate" and it seems hard for me to believe that most people will be willing to implement swept volumes or something like that.
