### ISSUE TITLE
What stops someone from hit-testing the entire room to generate a mesh?

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#6]
Based on the current design, nothing stops an app from just raytracing the entire room and generating a 3d mesh of your world. This seems like a potential privacy concern. Should the API be rate-limited?

**Comment by tbalouet** [comment]
Isn't there cases where the app's purpose would be just to do that (generate a mesh of the room)? Like for applications like this one: https://twitter.com/rrhoover/status/979340349305835520 to decorate an real room with virtual objects.

If so, how could we warn the user of such usage and allow them to prevent it?

**Comment by blairmacintyre** [comment]
The hit-test functionality is not intended to solve that problem.

There will need to be separate APIs for 
- accessing cameras and other sensors in the web page, to do arbitrary computer vision (see https://github.com/immersive-web/proposals/issues/4)
- accessing platform specific sensing, such as meshes on Hololens and planes on ARKit/ARCore, as well as any "thing" detection (see https://github.com/immersive-web/proposals/issues/3)

These are more complicated, both because of the permission issues, but also because they need to be done in a cross-platform way.

I imaging the custom CV will be easier;  we're already prototyping that in WebXR Viewer.  I expect that platform specific sensing will move slower because it's less well defined.

**Comment by lincolnfrog** [comment]
It sounds as though we are comfortable with there being a limit to hit-test rate. A specific "maximum useful" number sounds like a good approach rather than some arbitrary limit. I can see wanting to do a raycast for each controller and then one for a reticle and one for placing an object, since those are two separate cases. Given we probably don't support more than two controllers, is 4 a good limit? After 4 we can say "hit-test limit reached for this frame" in a promise rejection.

**Comment by blairmacintyre** [comment]
One question:  what the difference between "reticle and controllers" and "placing an object".  How do you place an object without using the reticle or controllers?  Are you thinking that the reticle is in a fixed place (center of screen) and placing an object is in response to some other direction?  How do we get it?  

Isn't the screen-based input really a stand-in for gaze, either eye-gaze or head-pose?  

We could take more of a lower bound approach:  e.g., we assert that all implementations need to support _at least_ the lower bound, but some can support more.  Could expose the max as a property.

I say this because as new control and input schemes become common, 4 may be too little.  For example, we have 10 fingers ... 

Or, we could couple it to the input controllers available, and make your rationale explicit:  the number of 3D/6D inputs available on the device. 
- head / device pose
- eye gaze (if available)
- ray-through-a-2d-screen-coordinate
- 3D/6D controller / finger / hand

Essentially, we want to know where each possible spatial input hits the world.

**Comment by lincolnfrog** [comment]
@NellWaliczek also suggested that we might disallow arbitrary rays entirely and just support only a device/input-source (and maybe an offset to support my example of wanting the reticle in the upper portion of the magic window rather than the center?).

**Comment by lincolnfrog** [comment]
That's interesting as it allows each browser to decide it's own privacy limitations? It does mean, however, that effectively apps have to assume only one-per and so that may not be different than enforcing it in the spec in practice...

**Comment by blairmacintyre** [comment]
> This gets back to the point about whether this is necessary at all - if we expose a bunch of world-understanding objects to JS anyway, what does it matter if you can do a bunch of hit tests to map the world? You can just request the mesh itself and that would be more efficient anyway.

My assumption is that the browser would expose a representation of the world that corresponds to whatever we put in the standard (i.e., a sparse mesh, perhaps?), but that the browser might be able to leverage _addition_ platform capabilities to do hit testing.

And, a browser might (for privacy reasons) only provide a subset of the available mesh (e.g., parts that the user has visited while the web page has had access).

In both cases, the hit test might provide hits that aren't in the exposed knowledge.

**Comment by blairmacintyre** [comment]
> The main distinction would be if there is a difference in permissions between just allowing the camera + hit-test vs. some kind of "world understanding" permission.

See https://blairmacintyre.me/2018/06/29/camera-access-webxr

I disagree with the way permissions are currently implemented in Chrome Canary.  The user is being presented a false question, since the WEB PAGE does not have access to the camera (the browser does).  

So, I think there should be different permissions:
- display camera 
- world knowledge (+ above)
- provide camera frames (+ above)

**Comment by lincolnfrog** [comment]
I think I understand your points about different implementations, but I don't understand the point about privacy wrt hit-test vs. meshes. "parts that the user visited while the web page had access" - if we start a new XR session each time you visit a web page, it seems like we only will have/expose world understanding related to the location the user has visited since loading the page (and granting permission). I also am a bit suspicious of the idea that we will make hit-test return from a richer set of data than is exposed via world-understanding. Generally speaking, at least today, we are *always* hitting a world-understanding object under the hood and I think our long-term plan is to return the id of the "trackable object" that was hit as part of hit results.

Your permission break down seems correct from a technical perspective but I think communication is so so hard on this. Does an average person understand what "provide camera frames" vs "display camera" means? This continues to be a very hard problem.

**Comment by blairmacintyre** [comment]
> I think I understand your points about different implementations, but I don't understand the point about privacy wrt hit-test vs. meshes. "parts that the user visited while the web page had access" - if we start a new XR session each time you visit a web page, it seems like we only will have/expose world understanding related to the location the user has visited since loading the page (and granting permission).

Consider Hololens.  When you fire up the display, and it recognizes the space you are in, it makes the entire mesh it knows about about available to the app.  It is unclear to me that it would be expected, or appropriate, to make all of this mesh available to a web app. 

In a "context free tracker" like current ARKit (and I assume ARCore), each session starts fresh.  That is not how these devices will work, eventually.  Especially HMDs.

> I also am a bit suspicious of the idea that we will make hit-test return from a richer set of data than is exposed via world-understanding. Generally speaking, at least today, we are always hitting a world-understanding object under the hood and I think our long-term plan is to return the id of the "trackable object" that was hit as part of hit results.

Key phrase is "at least today".  But even then, consider this:  ARKit can include (in the things it might do a hit test against) planes that it only has an estimate of, and that it has not yet turned into a plane anchor (i.e., exposed as part of the world info, to the app).  It can also hit against feature points.  A device with a depth camera may be able to hit test against the cloud and hit things that are not yet part of a mesh it might generate via SLAM techniques.

It would be up to the browser to decide what it wanted to hit against on these devices.  But it's unlikely that all of this info can (or even could) be exposed to the web page.

**Comment by blairmacintyre** [comment]
> Your permission break down seems correct from a technical perspective but I think communication is so so hard on this. Does an average person understand what "provide camera frames" vs "display camera" means? This continues to be a very hard problem.

Absolutely.  It's hard, and the text I chose for those boxes was "best effort" (with feedback from others here).  

I think this will be an ongoing process and require education of users.  But it's better than throwing up our hands and just saying "hey, if you want to do AR, you have to expose the camera to the web page."

**Comment by lincolnfrog** [comment]
Ok, thanks for clarifying your points about the hit-test vs world-understanding issue, those are good arguments. Does this require locking hit-testing to devices then it makes sense. If you can pass in an arbitrary ray, could you get a hit against part of the, for example, hololens mesh that is outside of the range of the current session?

**Comment by blairmacintyre** [comment]
I think that would be up to the browser ... you could image this would be something a user might want to be able to control via browser settings / options.

**Comment by johnpallett** [comment]
@blairmacintyre re: "web page does not have access to the camera" - is this true? I can't find language in the current XR spec (e.g. around session creation or compositing) that specifically addresses this (e.g.  preventing a site from using canvas.captureStream to access camera data). Do we need to add something (or did I miss this?)

**Comment by lincolnfrog** [comment]
The current spec doesn't address this point - it just talks about "world understanding"-style permissions and privacy concerns. I think we need a deeper discussion of permissions and privacy in the spec especially regarding the camera.

**Comment by blairmacintyre** [comment]
@johnpallett the spec does not say that apps should have access to the camera, nor does anything about the API suggest the apps would have access.  If an implementation is giving apps access to camera data, this seems a bug and massive security hole.

I'm pretty sure current WebGL semantics make it possible for certain things (like textures) to be prevented from being read back;  the same should be true of any data put into the GPU memory by the UA, and anything derived from it.  

For example, we MAY want to put camera video into a texture to enable rendering of reflections:  but if we do, any render target that is affected by that data needs to be marked as not being able to be read back.

Presumably with more advanced shaders and GPU activities that might come with WebGPU, etc., this will become trickier ... I'm not sure.

**Comment by johnpallett** [comment]
@blairmacintyre agreed re: reflection textures being worth a discussion. As written the spec doesn't require the UA to protect textures or mark an AR canvas as 'origin-clean'. We should probably move further discussion on camera data / XRSession to the WebXR repo (instead of here).

**Comment by blairmacintyre** [comment]
@johnpallett do you mind summarizing over there?  Perhaps talk with the other Googlers first? :)

**Comment by tencircles** [comment]
Chiming in here as well to say that limiting per-frame may mean different things for different displays. Unless the spec explicitly defines a frame as occurring at a specific interval, frames could conceivably occur anywhere from 30hz to 244hz as they do for rAF depending in the display's refresh rate.

**Comment by lincolnfrog** [comment]
> As long as we can do at least one hit-test per frame (2 may be better to support controllers), I'm fine with limiting number of hit-test calls per frame.

The best plan we had for rate limiting IMO was to limit to one per device (including controllers) per frame, so you would still be able to have a cursor on each controller and one representing gaze if you wanted.

That said, we are dubious that this actually adds much security and might just limit the API for no reason.

Interested in what people think about the idea of requiring ONLY device-relative hit-testing. That is potentially a more important limitation from a security perspective.

**Comment by blairmacintyre** [comment]
I've been thinking about 3 security levels (roughly), and device-relative fits nicely at the more secure levels:
- base:  device data + device-relative hit-testing.  I'm thinking that, perhaps, this should imply that only the ORIENTATION of the hit ray is specified, and that the start of the ray is the origin of the device frame
- world data:  world knowledge passed in.  Hit testing can now be done relative to that data, in addition to the device-relative hit-testing.  UA's may choose to provide coarser world data than the platform supports, so that high res meshes (for example) aren't provided
- all sensing: camera + high res meshes, etc.

I admit I'm still a little concerned about per-frame testing relative to device if the orientation of the hit ray can be changed every frame.  You can still, essentially, randomly scan the room, especially on high speed devices.  I'm not sure how to deal with this.

**Comment by judax** [comment]
There has been some research showing that direct manipulation on a touch screen can be a better approach for object placement/movement in smartphone based AR. Just wanted to mention that limiting hit test to relative-center-of-the-screen use cases might also limit these UX paths where a digital object needs to be placed with direct manipulation but still within the boundaries of a detected mesh/plane.

**Comment by blairmacintyre** [comment]
I didn't think that meant "relative to center of screen" ... that would be a terrible idea!   I meant "orientation relative to the pose of the device" ... so, rays that go through any point on the screen should be possible.

**Comment by kearwood** [comment]
Another reason for casting more than one ray per frame would be to implement a curved selection path (eg, a parabola representing the path of a projectile hitting the target).  If these cases are prevalent, perhaps we could provide these curved paths as explicit higher level hit test requests.

**Comment by lincolnfrog** [comment]
As per the f2f meeting discusssion on this topic, we agreed that any attempt to limit hit-test will likely leak the underlying API if the app does clever things - either using hit-test for scanning, however slowly, or UI tricks to get the user to do the scanning if we hide hit-test behind a user-gesture, for example.

We determined that, since the camera permission and sophisticated environment understanding access such as planes is included in the standard AR-mode type of session, that this question is really about how we support a "lite AR-mode" that doesn't require a permission equivalent to camera. It will be up to that lite-mode to fundamentally limit the scope of the underlying geometry that is available to lite sessions and that will include hit-test - basically hit-test will only interact with that limited subset of environment data that is constrained as part of the lite session. So closing this in favor of https://github.com/immersive-web/webxr/issues/402.
