### ISSUE TITLE
Add support for screen-space version of the API?

### ISSUE THREAD

**Issue by lincolnfrog** [immersive-web/hit-test#7]
Both ARCore and ARKit currently only provide a screen-space hit-test api. This API is extremely useful for AR on smartphones, though it is irrelevant to HMD AR. Should we support that API or require the developer to convert from screen-space to a ray?

**Comment by ddorwin** [comment]
One problem with such an approach is that content authors will need to support both mechanisms and test both paths. That may result in authors only using one path and thus apps not working on devices/clients that only support the other. It'd be better if there was a pattern (either required by the API or a simple best practice) that worked for both cases.

**Comment by blairmacintyre** [comment]
I'm not sure I see a reasonable way of avoiding both.  

- Devices with 6D controllers or (eventually) finger/hand tracking will need the full "ray" approach, as the vectors being hit-test will not intersect the screen.
- phones may need to restrict to just screen-based intersection until the underlying systems support arbitrary rays.

Now, it _may_ be that this discussion is moot, if screen-based AR libraries (e.g., ARKit and ARCore, at least) both end up supporting arbitrary vectors.  But, until we know that till happen.

I don't see the support as a big deal:  if an app is going to non-trivially support these different environments (e.g., from magic windows through full immersion, with screen-based and controller-based interaction) they are going to need to adapt to more than the hit-test parameter.  So switching from  `hitTest([sx,sy])` to `hitTest(matrix)` seems trivial, relative to the other things that have to change to support both kinds of UIs.

**Comment by lincolnfrog** [comment]
This support would also provide pixel-perfect reticle support as (0.5, 0.5) would apply to the next frame just as accurately as this frame.

**Comment by blairmacintyre** [comment]
Agreed!  I'd prefer to see both.

**Comment by lincolnfrog** [comment]
@blairmacintyre are you ok with losing the screen-space API if we support the relative ray + device-based frame-of-reference for accurate reticle and "screen space" style support. As David mentioned, you can always do your own math to project the screen coordinate into 3d space.

**Comment by blairmacintyre** [comment]
I think it's fine.  Doing "ray relative to some device frame of reference" instead of "ray + arbitrary origin" solve the problem, right?  The issue with ARKit is that you can  "only" shoot rays relative to the origin of the ARKit view coordinate frame (i.e., the screen / camera);  so requiring the programmer to specify the exact right origin was a big problem.  

Attaching the ray to the camera coordinate frame solves that problem;  sure, only rays that shoot through the screen are valid, but that's not a big deal.  We could include a simple javascript utility method for hit-testing that implements 2D screen-space hit-testing in the sample code (or polyfill), that automatically uses the right coordinate frame and creates the ray.  (In theory, this would work with HMDs, too, although it's probably not going to get used when there is a controller and no mouse/touch.)

**Comment by lincolnfrog** [comment]
Closing this in favor of a smaller API surface and relative rays
